[build]
target = "xtensa-esp32s3-espidf"
rustc-wrapper = "sccache"
rustflags = [
    "--cfg", "espidf_time64",
    "-C", "default-linker-libraries",
    "-C", "target-feature=-loop",
]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]

[env]
LIBCLANG_PATH = { value = ".embuild/esp-clang/lib", relative = true }
